
version: '3.8'

services:
  pg-master:
    container_name: bsupporter-pg-01
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'docker'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
     - '/var/lib/postgresql/data'
    ports:
      - target: 5432
        published: 9876
        mode: host

  pg-slave:
    container_name: bsupporter-pg-02
    depends_on:
      - pg-master
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'docker'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: 'pg-master'
    volumes:
     - '/var/lib/postgresql/data'
    ports:
      - target: 5432
        published: 9877
        mode: host
    links:
     - 'pg-master'
